version: "3.2"

services:
    geant4_version10.4:
        build: .
        image: ncastello/damicm-geant4.10.4:development

    damicm_prod:
        image: ncastello/damicm-geant4.10.4:production
        environment:
            - DISPLAY=unix${DISPLAY}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix

    damicm_dev:
        image: ncastello/damicm-geant4.10.4:development
        environment:
            - DISPLAY=unix${DISPLAY}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - type: bind
              source: /home/ncastello/repos/DAMIC-DAMIC-M/DAMICM_G4Sims
              target: /home/damicmuser/G4104Source
            - type: bind
              source: /home/ncastello/workdir/DAMICM/simulations/G4104Run
              target: /home/damicmuser/G4104Run
            - type: bind
              source: /home/ncastello/repos/PyAnUtils
              target: /home/damicmuser/PyAnUtils
            - type: bind
              source: /home/ncastello/repos/pydamicm
              target: /home/damicmuser/pydamicm

    damicSNOLAB:
        image: ncastello/damicm-geant4.10.4:latest
        environment:
            - DISPLAY=unix${DISPLAY}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - type: bind
              source: /home/ncastello/workdir/DAMIC/simulations/G4104Run
              target: /home/damicmuser/G4104Run
            - type: bind
              source: /home/ncastello/repos/DAMIC-DAMIC-M/DAMIC100_G4outchanged
              target: /home/damicmuser/G4104Source



    damic100:
        image: ncastello/damicm-geant4.10.4:latest
        environment:
            - DISPLAY=unix${DISPLAY}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - type: bind
              source: /home/ncastello/repos/DAMIC-DAMIC-M/DAMICSNOLAB_G4sims
              target: /home/damicmuser/G4104Source
            - type: bind
              source: /home/ncastello/workdir/DAMIC100/simulations/G4104Run
              target: /home/damicmuser/G4104Run

    recon:
        image: ncastello/damicm-geant4.10.4:development
        environment:
            - DISPLAY=unix${DISPLAY}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - type: bind
              source: /home/ncastello/repos/recon
              target: /home/damicmuser/G4104Run


